---
- hosts: localhost
  gather_facts: yes
#  remote_user: root
#  become: yes
  tasks:
    - name: Gather EC2 facts.
      ec2_remote_facts:
        region: us-west-2
      register: ec2_facts
    - name: Debug
      debug:
        msg: "{{ ec2_remote_facts }}"
#    {% endraw %}
