---
- hosts: servers
  remote_user: root
  become: yes
  gather_facts: no
  tasks:
    - name: checking the status of register concept
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - tree
        - finger
        - curl
      register: report
    - debug: var=report
