---
- hosts: 192.168.50.64
  remote_user: root
  become: yes
  gather_facts: false
  tasks:
    - name: install packages
      yum:
        name: httpd
        state: present
    - name: copy information    
      copy:
        src: /ansible/simple.html
        dest: /var/www/html/simple.html
      notify: start httpd service
  handlers:
    - name: start httpd
      service:  
        name: httpd
        state: started
#   - name: service start
#     service: 
#       name: httpd
#       state: started
