---
- hosts: servers 
  remote_user: root
  gather_facts: no
  tasks:        
    - name: copy val.j2 by using template mechanism 
      template:
        src: /ansible/roles/validate/templates/val.j2
        dest: /tmp/val                  
    - name: copy test.html.j2 
      template: 
        src: /test.html.j2
        dest: /var/www/html/test.html
      notify: restart httpd service

  handlers: 
    - name: restart httpd service
      service: 
        name: httpd
        state: restarted
