--- 
- hosts: all 
  tasks:
    - name: "loop through list"
      debug:
        msg: "An item: {{ item}}"
      with_items:
        - 1
        - 2
        - 3
    - name: add several  users
      user:
        name: "{{item }}" 
        groups: "wheel"
        state: present
      with_items:
        - testuser1
        - testuser2
    - name: " loop through list from a variable"
      debug:
        msg: " An item: {{item}}"
      with_items: "{{ somelist }}"
    - name: more complex items to add several users
      user:
        name: "{{item.name}}"
        uid: "{{ item.uid }}"
        groups: "{{ item.groups }}"
        state: present
      with_items:
        - { name: testuser1, uid: 1008, groups: "wheel, staff" }
        - { name: testuser2, uid: 1009, groups: staff }

        
