- name: Start instances
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    instance_ids:
      - 'i-0bef02b91da693733'
    region: us-west-2
  tasks:
    - name: Start the instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: running
        wait: True
        vpc_subnet_id: subnet-d54610ac
        assign_public_ip: yes
